### PR TITLE
updating to react 17.0.1 dependency

### PR DESCRIPTION
**Pull request by marsch**
i've updated the react and react-native dependencies to solve #85

### CODE REVIEW

**Comment by RayHughes** [comment]
Thank you!

**Comment by nmokkenstorm** [comment]
While I appreciate the effort, shouldn't this be a peerDependency? I feel like this upgrade will break the existing behaviour for a lot of people stuck on React 16 for whatever reason.

**Comment by RayHughes** [comment]
@nmokkenstorm I can't speak for the PR author, but the outdated version of React Native dependency is causing issues for some of us who have a requirement to be on 17.

**Comment by robmadole** [comment]
If this PR can be updated so that it allows both React 16 and 17 I'll get it merged and cut a release. But I don't have time at the moment to deal with figuring out NPM 7 peer dependency changes (they have some kind of backward-incompatible thing they did recently)

**Comment by marsch** [comment]
@robmadole am trying to get my head around it. As far as I understood, react-native 0.64 depends on react 17, right? Am actually not sure what you mean by supporting 16 and 17.  Can you point me to a source where to look it up, so I can get this working for you?

**Comment by matkastner** [comment]
@robmadole @marsch how about this: #98 ?

**Comment by robmadole** [comment]
I merged #98 and have released a new version 0.2.7. For any interested, give this a spin and see if it resolves the problem.

**Comment by matkastner** [comment]
Thanks for the quick response @robmadole! Will give it a try this morning 🕺

**Pull request closed without merging**
