### PR TITLE
fixed "Warning: FontAwesomeIcon: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead."

### LINKED ISSUE #170: Warning: FontAwesomeIcon: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
**Describe the bug**
When building with React Native 0.74.0, I get the following error on use of `<FontAwesomeIcon>`

**Reproducible test case**
Include a URL (codepen.io, jsfiddle.net, Git repository, codesandbox.io, stackblitz.com, etc.) that demonstrates the problem.

**Expected behavior**
No warnings generated

**Desktop (please complete the following information):**
```
react-native@0.74.0:
  version "0.74.0"

react@18.2:
  version "18.2.0"

"@fortawesome/pro-solid-svg-icons@^6.1.2":
  version "6.5.2"

"@fortawesome/react-fontawesome@0.2.0":
  version "0.2.0"

"@fortawesome/react-native-fontawesome@^0.3.0":
  version "0.3.0"
```

**Additional context**

### PR DESCRIPTION
**Pull request by gregmarut**
fixes #170

### CODE REVIEW

**Comment by Willham12** [comment]
lgtm

**Review by lid3rs — APPROVED** [review]

**Comment by robmadole** [comment]
Thank you for this! Getting it released now.

**Comment by renchap** [comment]
This PR has issues, for example if you pass `<FontAwesomeIcon style={undefined}>`, then it will fail with "Cant's read property `color` of `undefined`"

**Comment by robmadole** [comment]
I've addressed this with 0.3.2 I believe. And I've got some tests in place now to guard against all the props with `undefined` values being passed.

**Pull request merged**
